server.port=8082
spring.application.name=course-service

# Cấu hình kết nối MySQL (Đã thêm tham số chống lỗi kết nối)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3003/course_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345

# Khai báo Dialect trực tiếp (Giúp app không bị crash nếu MySQL phản hồi chậm)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true